/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedTrashIndexRouteImport } from './routes/_authed/trash/index'
import { Route as AuthedThreadsIndexRouteImport } from './routes/_authed/threads/index'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks/index'
import { Route as AuthedMarketingTypesIndexRouteImport } from './routes/_authed/marketing-types/index'
import { Route as AuthedInquiriesIndexRouteImport } from './routes/_authed/inquiries/index'
import { Route as AuthedExpensesIndexRouteImport } from './routes/_authed/expenses/index'
import { Route as AuthedExpenseCategoriesIndexRouteImport } from './routes/_authed/expense-categories/index'
import { Route as AuthedContactsIndexRouteImport } from './routes/_authed/contacts/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedCalendarIndexRouteImport } from './routes/_authed/calendar/index'
import { Route as AuthedAuditIndexRouteImport } from './routes/_authed/audit/index'
import { Route as AuthedTasksNewRouteImport } from './routes/_authed/tasks/new'
import { Route as AuthedThreadsPostIdIndexRouteImport } from './routes/_authed/threads/$postId/index'
import { Route as AuthedTasksTaskIdIndexRouteImport } from './routes/_authed/tasks/$taskId/index'
import { Route as AuthedInquiriesSubmissionIdIndexRouteImport } from './routes/_authed/inquiries/$submissionId/index'
import { Route as AuthedClientsClientIdIndexRouteImport } from './routes/_authed/clients/$clientId/index'
import { Route as AuthedTasksTaskIdEditRouteImport } from './routes/_authed/tasks/$taskId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_authed.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/dashboard.lazy').then((d) => d.Route),
)
const AuthedTrashIndexRoute = AuthedTrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/trash/index.lazy').then((d) => d.Route),
)
const AuthedThreadsIndexRoute = AuthedThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/threads/index.lazy').then((d) => d.Route),
)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/tasks/index.lazy').then((d) => d.Route),
)
const AuthedMarketingTypesIndexRoute =
  AuthedMarketingTypesIndexRouteImport.update({
    id: '/marketing-types/',
    path: '/marketing-types/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/marketing-types/index.lazy').then((d) => d.Route),
  )
const AuthedInquiriesIndexRoute = AuthedInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/inquiries/index.lazy').then((d) => d.Route),
)
const AuthedExpensesIndexRoute = AuthedExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/expenses/index.lazy').then((d) => d.Route),
)
const AuthedExpenseCategoriesIndexRoute =
  AuthedExpenseCategoriesIndexRouteImport.update({
    id: '/expense-categories/',
    path: '/expense-categories/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/expense-categories/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedContactsIndexRoute = AuthedContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/contacts/index.lazy').then((d) => d.Route),
)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/clients/index.lazy').then((d) => d.Route),
)
const AuthedCalendarIndexRoute = AuthedCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/calendar/index.lazy').then((d) => d.Route),
)
const AuthedAuditIndexRoute = AuthedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/audit/index.lazy').then((d) => d.Route),
)
const AuthedTasksNewRoute = AuthedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/tasks/new.lazy').then((d) => d.Route),
)
const AuthedThreadsPostIdIndexRoute =
  AuthedThreadsPostIdIndexRouteImport.update({
    id: '/threads/$postId/',
    path: '/threads/$postId/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/threads/$postId/index.lazy').then((d) => d.Route),
  )
const AuthedTasksTaskIdIndexRoute = AuthedTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/tasks/$taskId/index.lazy').then((d) => d.Route),
)
const AuthedInquiriesSubmissionIdIndexRoute =
  AuthedInquiriesSubmissionIdIndexRouteImport.update({
    id: '/inquiries/$submissionId/',
    path: '/inquiries/$submissionId/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/inquiries/$submissionId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedClientsClientIdIndexRoute =
  AuthedClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/clients/$clientId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedTasksTaskIdEditRoute = AuthedTasksTaskIdEditRouteImport.update({
  id: '/tasks/$taskId/edit',
  path: '/tasks/$taskId/edit',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/tasks/$taskId/edit.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/audit/': typeof AuthedAuditIndexRoute
  '/calendar/': typeof AuthedCalendarIndexRoute
  '/clients/': typeof AuthedClientsIndexRoute
  '/contacts/': typeof AuthedContactsIndexRoute
  '/expense-categories/': typeof AuthedExpenseCategoriesIndexRoute
  '/expenses/': typeof AuthedExpensesIndexRoute
  '/inquiries/': typeof AuthedInquiriesIndexRoute
  '/marketing-types/': typeof AuthedMarketingTypesIndexRoute
  '/tasks/': typeof AuthedTasksIndexRoute
  '/threads/': typeof AuthedThreadsIndexRoute
  '/trash/': typeof AuthedTrashIndexRoute
  '/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/inquiries/$submissionId/': typeof AuthedInquiriesSubmissionIdIndexRoute
  '/tasks/$taskId/': typeof AuthedTasksTaskIdIndexRoute
  '/threads/$postId/': typeof AuthedThreadsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/audit': typeof AuthedAuditIndexRoute
  '/calendar': typeof AuthedCalendarIndexRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/contacts': typeof AuthedContactsIndexRoute
  '/expense-categories': typeof AuthedExpenseCategoriesIndexRoute
  '/expenses': typeof AuthedExpensesIndexRoute
  '/inquiries': typeof AuthedInquiriesIndexRoute
  '/marketing-types': typeof AuthedMarketingTypesIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/threads': typeof AuthedThreadsIndexRoute
  '/trash': typeof AuthedTrashIndexRoute
  '/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/clients/$clientId': typeof AuthedClientsClientIdIndexRoute
  '/inquiries/$submissionId': typeof AuthedInquiriesSubmissionIdIndexRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdIndexRoute
  '/threads/$postId': typeof AuthedThreadsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/tasks/new': typeof AuthedTasksNewRoute
  '/_authed/audit/': typeof AuthedAuditIndexRoute
  '/_authed/calendar/': typeof AuthedCalendarIndexRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
  '/_authed/contacts/': typeof AuthedContactsIndexRoute
  '/_authed/expense-categories/': typeof AuthedExpenseCategoriesIndexRoute
  '/_authed/expenses/': typeof AuthedExpensesIndexRoute
  '/_authed/inquiries/': typeof AuthedInquiriesIndexRoute
  '/_authed/marketing-types/': typeof AuthedMarketingTypesIndexRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
  '/_authed/threads/': typeof AuthedThreadsIndexRoute
  '/_authed/trash/': typeof AuthedTrashIndexRoute
  '/_authed/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/_authed/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/_authed/inquiries/$submissionId/': typeof AuthedInquiriesSubmissionIdIndexRoute
  '/_authed/tasks/$taskId/': typeof AuthedTasksTaskIdIndexRoute
  '/_authed/threads/$postId/': typeof AuthedThreadsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/tasks/new'
    | '/audit/'
    | '/calendar/'
    | '/clients/'
    | '/contacts/'
    | '/expense-categories/'
    | '/expenses/'
    | '/inquiries/'
    | '/marketing-types/'
    | '/tasks/'
    | '/threads/'
    | '/trash/'
    | '/tasks/$taskId/edit'
    | '/clients/$clientId/'
    | '/inquiries/$submissionId/'
    | '/tasks/$taskId/'
    | '/threads/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/tasks/new'
    | '/audit'
    | '/calendar'
    | '/clients'
    | '/contacts'
    | '/expense-categories'
    | '/expenses'
    | '/inquiries'
    | '/marketing-types'
    | '/tasks'
    | '/threads'
    | '/trash'
    | '/tasks/$taskId/edit'
    | '/clients/$clientId'
    | '/inquiries/$submissionId'
    | '/tasks/$taskId'
    | '/threads/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/tasks/new'
    | '/_authed/audit/'
    | '/_authed/calendar/'
    | '/_authed/clients/'
    | '/_authed/contacts/'
    | '/_authed/expense-categories/'
    | '/_authed/expenses/'
    | '/_authed/inquiries/'
    | '/_authed/marketing-types/'
    | '/_authed/tasks/'
    | '/_authed/threads/'
    | '/_authed/trash/'
    | '/_authed/tasks/$taskId/edit'
    | '/_authed/clients/$clientId/'
    | '/_authed/inquiries/$submissionId/'
    | '/_authed/tasks/$taskId/'
    | '/_authed/threads/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trash/': {
      id: '/_authed/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof AuthedTrashIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/threads/': {
      id: '/_authed/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof AuthedThreadsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/marketing-types/': {
      id: '/_authed/marketing-types/'
      path: '/marketing-types'
      fullPath: '/marketing-types/'
      preLoaderRoute: typeof AuthedMarketingTypesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inquiries/': {
      id: '/_authed/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof AuthedInquiriesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/expenses/': {
      id: '/_authed/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthedExpensesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/expense-categories/': {
      id: '/_authed/expense-categories/'
      path: '/expense-categories'
      fullPath: '/expense-categories/'
      preLoaderRoute: typeof AuthedExpenseCategoriesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contacts/': {
      id: '/_authed/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthedContactsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar/': {
      id: '/_authed/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthedCalendarIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit/': {
      id: '/_authed/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthedAuditIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/new': {
      id: '/_authed/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthedTasksNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/threads/$postId/': {
      id: '/_authed/threads/$postId/'
      path: '/threads/$postId'
      fullPath: '/threads/$postId/'
      preLoaderRoute: typeof AuthedThreadsPostIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/': {
      id: '/_authed/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AuthedTasksTaskIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inquiries/$submissionId/': {
      id: '/_authed/inquiries/$submissionId/'
      path: '/inquiries/$submissionId'
      fullPath: '/inquiries/$submissionId/'
      preLoaderRoute: typeof AuthedInquiriesSubmissionIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$clientId/': {
      id: '/_authed/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/edit': {
      id: '/_authed/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof AuthedTasksTaskIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedTasksNewRoute: typeof AuthedTasksNewRoute
  AuthedAuditIndexRoute: typeof AuthedAuditIndexRoute
  AuthedCalendarIndexRoute: typeof AuthedCalendarIndexRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
  AuthedContactsIndexRoute: typeof AuthedContactsIndexRoute
  AuthedExpenseCategoriesIndexRoute: typeof AuthedExpenseCategoriesIndexRoute
  AuthedExpensesIndexRoute: typeof AuthedExpensesIndexRoute
  AuthedInquiriesIndexRoute: typeof AuthedInquiriesIndexRoute
  AuthedMarketingTypesIndexRoute: typeof AuthedMarketingTypesIndexRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
  AuthedThreadsIndexRoute: typeof AuthedThreadsIndexRoute
  AuthedTrashIndexRoute: typeof AuthedTrashIndexRoute
  AuthedTasksTaskIdEditRoute: typeof AuthedTasksTaskIdEditRoute
  AuthedClientsClientIdIndexRoute: typeof AuthedClientsClientIdIndexRoute
  AuthedInquiriesSubmissionIdIndexRoute: typeof AuthedInquiriesSubmissionIdIndexRoute
  AuthedTasksTaskIdIndexRoute: typeof AuthedTasksTaskIdIndexRoute
  AuthedThreadsPostIdIndexRoute: typeof AuthedThreadsPostIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedTasksNewRoute: AuthedTasksNewRoute,
  AuthedAuditIndexRoute: AuthedAuditIndexRoute,
  AuthedCalendarIndexRoute: AuthedCalendarIndexRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
  AuthedContactsIndexRoute: AuthedContactsIndexRoute,
  AuthedExpenseCategoriesIndexRoute: AuthedExpenseCategoriesIndexRoute,
  AuthedExpensesIndexRoute: AuthedExpensesIndexRoute,
  AuthedInquiriesIndexRoute: AuthedInquiriesIndexRoute,
  AuthedMarketingTypesIndexRoute: AuthedMarketingTypesIndexRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
  AuthedThreadsIndexRoute: AuthedThreadsIndexRoute,
  AuthedTrashIndexRoute: AuthedTrashIndexRoute,
  AuthedTasksTaskIdEditRoute: AuthedTasksTaskIdEditRoute,
  AuthedClientsClientIdIndexRoute: AuthedClientsClientIdIndexRoute,
  AuthedInquiriesSubmissionIdIndexRoute: AuthedInquiriesSubmissionIdIndexRoute,
  AuthedTasksTaskIdIndexRoute: AuthedTasksTaskIdIndexRoute,
  AuthedThreadsPostIdIndexRoute: AuthedThreadsPostIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
